### ISSUE TITLE
jQuery independent or completely dependent ?

### ISSUE THREAD

**Issue by ktkaushik** [ktkaushik/editor#2]
Make it completely jQuery independent ?

Would that make the code bloated ?

**Comment by sankalpsans** [comment]
Let's carve out the parts we want from jQuery and use them. We won't be using half the library anyway.

**Comment by ktkaushik** [comment]
If we keep carving out, then we will always have to keep coming back to it for updating the new methods. On a longer run, do you think we might face the legacy code issue ?

**Comment by ktkaushik** [comment]
And in all honesty, who's to say that we wouldn't want to use small itsy-bitsy jQuery library in the future.

jQuery gives that flexibility for sure. cc @divyenduz

**Comment by sankalpsans** [comment]
@ktkaushik Let's keep jQuery for now, till we can find of a better way to manage dependencies of functions from within jQuery.
Also, is this targeted for online WYSIWYG editing? In that case, the leaner, the better.

**Comment by ktkaushik** [comment]
It is targeted towards WYSIWYG ?

Browser incompatibility is a major issue. Test this one on FF

**Comment by divyenduz** [comment]
We can start with keeping the famous ones in, like _, $
When the whole concept is built in form of an MVP, we can slowly remove dependencies to make it more lean. 
I would suggest that we let it take shape in less time and then figure out where it goes.

**Comment by ktkaushik** [comment]
Lodash over underscore.

**Comment by ktkaushik** [comment]
I am not too sure i completely agree with removing dependencies as we move along; the reason being that if we use any libraries then we are gonna make full use of it. Slowly, our ecosystem would start revolving around it. 

Later, we would have too many issues deciding to remove it and then redo a lot of stuff.

But then again there are chances that we might not even need to remove it. Ever.

**Comment by divyenduz** [comment]
I am not sure how big of a chunk will we use from these libraries, if we use huge parts of these ( by huge I mean, when it is a pain to remove them ), then it is fine I think to have them forever. 
If we are only using a small part of these, we can replace them. 
I am in favor of postponing the decision about these to the actual point where we have to make a decision.

**Comment by ktkaushik** [comment]
Postponing is just easy and i don't want that. Let's have jQuery.

I'm closing this. @sankalpsans has already agreed to have it in place.
